const deckData = [
    // pronouns, greetings, how to address

    { "hanzi": "我", "pinyin": "wo3", "english": "I; me" },
    { "hanzi": "你", "pinyin": "ni3", "english": "you" },
    { "hanzi": "他", "pinyin": "ta1", "english": "he" },
    { "hanzi": "她", "pinyin": "ta1", "english": "she" },
    { "hanzi": "它", "pinyin": "ta1", "english": "it" },
    { "hanzi": "我们", "pinyin": "wo3 men5", "english": "we" },
    { "hanzi": "你们", "pinyin": "ni3 men5", "english": "you (plural)" },
    { "hanzi": "他们", "pinyin": "ta1 men5", "english": "they (masculine)" },
    { "hanzi": "她们", "pinyin": "ta1 men5", "english": "they (feminine)" },
    { "hanzi": "你好", "pinyin": "ni3 hao3", "english": "hello (familiar)" },
    { "hanzi": "你们好", "pinyin": "ni3 men5 hao3", "english": "hello (formal/plural)" },
    { "hanzi": "早上好", "pinyin": "zao3 shang4 hao3", "english": "good morning" },
    { "hanzi": "午安", "pinyin": "wu3 an1", "english": "good afternoon" },
    { "hanzi": "晚上好", "pinyin": "wan3 shang4 hao3", "english": "good evening" },
    { "hanzi": "问好", "pinyin": "wen4 hao3", "english": "to say hello" },
    { "hanzi": "问候", "pinyin": "wen4 hou4", "english": "greeting (noun)" },
    { "hanzi": "欢迎", "pinyin": "huan1 ying2", "english": "to greet; welcome" },
    { "hanzi": "你好吗", "pinyin": "ni3 hao3 ma5", "english": "how are you?" },
    { "hanzi": "有", "pinyin": "you3", "english": "to have; there is" },
    { "hanzi": "什么", "pinyin": "shen2 me5", "english": "what" },
    { "hanzi": "新", "pinyin": "xin1", "english": "new" },
    { "hanzi": "消息", "pinyin": "xiao1 xi5", "english": "news; message" },
    { "hanzi": "再见", "pinyin": "zai4 jian4", "english": "goodbye" },
    { "hanzi": "回头见", "pinyin": "hui2 tou2 jian4", "english": "see you soon" },
    { "hanzi": "说再见", "pinyin": "shuo1 zai4 jian4", "english": "to say goodbye" },
    { "hanzi": "谢谢", "pinyin": "xie4 xie5", "english": "thank you" },
    { "hanzi": "多谢", "pinyin": "duo1 xie4", "english": "thank you very much" },
    { "hanzi": "不客气", "pinyin": "bu2 ke4 qi5", "english": "you're welcome" },
    { "hanzi": "不用谢谢", "pinyin": "bu2 yong4 xie4 xie5", "english": "don't mention it" },
    { "hanzi": "没什么", "pinyin": "mei2 shen2 me5", "english": "it was nothing" },
    { "hanzi": "请原谅", "pinyin": "qing3 yuan2 liang4", "english": "excuse me" },
    { "hanzi": "道歉", "pinyin": "dao4 qian4", "english": "to apologize; apology" },
    { "hanzi": "我道歉", "pinyin": "wo3 dao4 qian4", "english": "my apologies" },
    { "hanzi": "对不起", "pinyin": "dui4 bu5 qi3", "english": "I'm sorry" },
    { "hanzi": "原谅", "pinyin": "yuan2 liang4", "english": "to forgive" },
    { "hanzi": "请", "pinyin": "qing3", "english": "please" },
    { "hanzi": "别忘了", "pinyin": "bie2 wang4 le5", "english": "don't forget" },
    { "hanzi": "当然", "pinyin": "dang1 ran2", "english": "certainly; of course" },
    { "hanzi": "当然不是", "pinyin": "dang1 ran2 bu2 shi4", "english": "of course not" },
    { "hanzi": "同意", "pinyin": "tong2 yi4", "english": "okay; agree" },
    { "hanzi": "够了", "pinyin": "gou4 le5", "english": "that's enough" },
    { "hanzi": "先生", "pinyin": "xian1 sheng5", "english": "mister; sir" },
    { "hanzi": "夫人", "pinyin": "fu1 ren5", "english": "ma'am; Mrs." },
    { "hanzi": "姑娘", "pinyin": "gu1 niang5", "english": "miss; young lady" },
    { "hanzi": "年轻人", "pinyin": "nian2 qing1 ren2", "english": "young man; young person" },
    { "hanzi": "小男孩", "pinyin": "xiao3 nan2 hai2", "english": "young boy; little boy" },
    { "hanzi": "小女孩", "pinyin": "xiao3 nv3 hai2", "english": "young girl; little girl" }
];